config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users

  root 'series#index'

  get 'admin/dashboard', to: 'series#dashboard'
  get 'admin/users', to: 'series#users'
  get 'admin/series/:id', to: 'series#show_admin_view', as: :series_admin_view
  get 'request-callback', to: 'series#callback'
  resources :series do
    

    member do
      post 'publish'
      post 'unpublish'
      

    end

    collection do
      get 'browse'
      get 'search'

      get 'subscriptions'
      post 'browse'
      
    end
    resources :episodes
    resources :orders do
      collection do
        get 'buy'
        get 'rent'
      end
    end
  end
  

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController


before_action :authenticate_user!, except: [:index, :show, :browse, :search, :callback]
before_action :current_user_admin?, except: [:index, :show, :browse, :search, :subscriptions, :callback ]
before_action :find_series, only: [:show, :show_admin_view, :edit, :update, :destroy, :publish, :unpublish]

  def index
    @series = Series.order(created_at: :desc).where(publish: true).limit(8)
  end

  def new
  	@series = Series.new
  end

  def create
  	@series = Series.new(series_params)
  	 if @series.save
  	 	redirect_to @series
  	 else
  	 	render :new
  	 end
  end

  def show
    @episodes = Episode.where(series_id: params[:id]).order(episode_order: :asc)
  end

  def show_admin_view
    @episodes = Episode.where(series_id: params[:id])
  end

  def edit
  end

  def update
    # AppMailer.welcome_email(current_user).deliver_now  

    if @series.update(series_params)

      flash[:notice] = "Series updated successfully !!"
      redirect_to @series
    else

      flash[:notice] = "Something went wrong, please retry !!"
      render 'edit'
    end
  end

  def destroy
    @series.destroy

      flash[:notice] = "Series deleted successfully !!"

    redirect_to :back
  end

  def publish
    @series.publish = true
    if @series.save

      flash[:notice] = "Series published successfully !!"
      redirect_to :back
    else

      flash[:notice] = "Something went wrong, please retry !!"
      redirect_to root_url
    end
  end

  def unpublish
    @series.publish = false
    if @series.save

      flash[:notice] = "Series un-published successfully !!"
      redirect_to :back
    else

      flash[:notice] = "Something went wrong, please retry !!"
      redirect_to root_url
    end
  end

  def search
    if params[:search].present?
      @series = Series.where("lower(title) LIKE ?","%#{params[:search].downcase}%")
    else
      @series = Series.order(created_at: :desc).where(publish: true)
    end

    render 'browse'
  end

  def browse
    
    if params[:filter_difficulty].present? 
      @series = Series.where("lower(difficulty) LIKE ?","%#{params[:filter_difficulty].downcase}%")
      # @filter_difficulty = params[:filter_difficulty]

    else
      @series = Series.order(created_at: :desc).where(publish: true)
    end
    


    respond_to do |f|
      f.html
      f.js
    end
  end

  def dashboard
    @series = Series.all()
      
  end

  def subscriptions
    @orders = Order.where(user_id: current_user.id).where.not(series_id: nil).order(created_at: :desc)
  end

  def callback
    @series = Series.order(created_at: :desc).where(publish: true).limit(2)
    
  end

  def users 
    @users = User.all
  end


  private
	def find_series
		@series = Series.find(params[:id])
	end
	def series_params
		params.require(:series).permit(:title, :description,:no_of_lessons,:difficulty,:trailer,
									   :rent_price,:buyout_price,:series_banner )
	end

  def current_user_admin?
    if user_signed_in?
      if !current_user.admin
        flash[:notice] = "You are not authorised to this page"
        
        redirect_to root_url

      end  
      

    end 
    
  end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= tinymce_assets %>


<%= form_for @series do |f| %>
	<% if @series.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@series.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @series.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :title %>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :description %>
	<%= f.text_area :description, :class => "tinymce", :rows => 10, :cols => 20  %>
	<%= tinymce %><br><br>
	<%= f.label :no_of_lessons %>
	<%= f.text_field :no_of_lessons %><br>
	<br>
	<%= f.label :series_banner %>
	<%= f.text_field :series_banner %><br>
	<br>
	<%= f.label :difficulty %>
	

	<%= f.select :difficulty, options_for_select([['Basic', 'Basic'], 
                                                     ['Intermediate', 'Intermediate'], 
                                                     ['Advanced', 'Advanced']
                                                     ]) %>

	
	<br>
	<%= f.label :trailer %>
	<%= f.text_area :trailer %><br>
	<br>
	
	<%= f.label :rent_price %>
	<%= f.text_field :rent_price %><br>
	<br>
	<%= f.label :buyout_price %>
	<%= f.text_field :buyout_price %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/series/_homepage_about_trainer.html.erb
<section class="section-about-trainer">
        <div class="row">
            <div class="col span-1-of-2"></div>
            <div class="col span-1-of-2">
                <h3 style="text-align: center;color: #fff;margin-bottom: 20px;"><u>About me</u></h3>
                <p>Alright guys! Love me or hate me for what I am going to say. As they say, I am going to speak the truth and nothing apart the truth. 
                </p>

                <p>There may a good chance you may already know me. If you don't, here I am. A veteran in the SFDC community and ex-engineer at Salesforce.com. Having spoken at a lot of meet-ups and conferences does make me an evangelist of salesforce.com. An evangelist of anything I believe by birth and having coded 100+ prototypes, gives me enough credidibility to at least train people on this kickass platform.</p>

                <p>
                Well, my students say I am good at teaching SFDC, but you are the best judge.  Let me be honest, if you want to know if you can excel in becoming a Salesforce.com specialist see if you like the demo link I have attached. Only and only if you want to be a specialist. 
                </p>        
                <p>
                    Let's be honest guys, this place is all about code, code and code. If you are expecting effortless efforts,boring PPT’s and dont want to go through previously written code, wait up. 
                </p>
                <p>
                    This may be the only site where each and every functionality is coded on air.
                </p>
                <p>
                    I can go on and on about the awesomeness of salesforce casts, but I better let you experience it.
                </p>
                <p>
                    Do share the feedback. It will only help me :)
                </p>
                <p>
                    Happy Hacking. I ve got your back, mate! 
                </p>
                <p>
                    Cheers,
                </p>
                <p>
                    Just call me KT
                </p>
            </div>    
        </div>
        
        
    </section>

app/views/series/_homepage_header.html.erb
<header class="header">
        <nav>
            <div class="row">
                <%= link_to 'Salesforce Casts',root_path, class: 'logo logo-inner' %>
                

                <ul class="main-nav">
                

                 <% if user_signed_in? && current_user.admin? -%>
                    <li><%= link_to 'Dashboard', admin_dashboard_path %></li>
                    <li><%= link_to 'User', admin_users_path %></li>
                    <li><%= link_to 'New Series', new_series_path %></li>
                    <li><%= link_to 'Account', edit_user_registration_path %></li>
                    <li><%= link_to 'Logout',destroy_user_session_path, :method => :delete %></li>

                <% elsif user_signed_in? &&  !current_user.admin? %>

                    <li><%= link_to 'Subscriptions', subscriptions_series_index_path %></li>
                    <li><%= link_to 'Account', edit_user_registration_path %></li>
                    <li><%= link_to 'Logout',destroy_user_session_path, :method => :delete %></li>
            
                <% else -%>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                    <li><%= link_to 'Sign up', new_user_registration_path,class:'btn btn-ghost' %></li>
                <% end -%>


                    
                </ul>
            </div>
        </nav>

        <div class="hero-text-box">
            <h1>Subscribe &nbsp;&nbsp;&amp;&nbsp;&nbsp; Enjoy your SFDC tv</h1>
            <%= link_to 'Browse', browse_series_index_path, class:'btn btn-full' %>
            <%= link_to 'Request Callback', request_callback_path, class:'btn btn-ghost' %>
           
        </div>
    </header>

app/views/series/_homepage_recent_series.html.erb
 <section class="section-fs">
        <div class="row">
            <p class="sec-title">Tune In. &nbsp;&nbsp;Sit Back. &nbsp;&nbsp;Become a Salesforce.com Master.</p>
        </div>
        <div class="row">
            <h2>Recent Series</h2>
        </div>

        
<div class="row">

            <% @series.each do |series| %>
            
            <div class="col span-1-of-4 box">
                <div class="recent-series">

                    <img src="<%= series.series_banner %>">
                    <div class="recent-series-icard">
                        <div class="skill-lvl-count">
        
                            <p class="skill-level"><%= series.difficulty %></p>
                            <p class="video-count">
        
                                <span><%= series.no_of_lessons %></span>
                                <span class="video-key-word">videos</span>
                            </p>
                        </div>
                        <div class="series-title">
        
                            <%= link_to series.title,series_path(series) %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
            
            
        </div>

    </section>

        <% if false %>

        <div class="row">

            <% @series.each do |series| %>

            <div class="col span-1-of-4 box">
                <div class="recent-series">

                    <img src="../assets/series6.jpg">
                    <div class="recent-series-icard">
                        <div class="skill-lvl-count">
        
                            <p class="skill-level"><%= series.difficulty %></p>
                            <p class="video-count">
        
                                <span><%= series.no_of_lessons %></span>
                                <span class="video-key-word">videos</span>
                            </p>
                        </div>
                        <div class="series-title">
        
                            <div class="series-title"><a href="series.html"><%= link_to series.title,series_path(series) %></a> </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
            
            
        </div>
        
    <% end %>

app/views/series/_series_filter.html.erb
<%= form_tag browse_series_index_path, remote: true, id: 'filter_difficulty_form', class: 'filter_difficulty'  do %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
<% [ 'Intermediate', 'Medium', 'Difficulty'].each do |filter_difficulty| %>
      <%= radio_button_tag 'filter_difficulty', filter_difficulty, params[:filter_difficulty] == filter_difficulty, class: 'filter_difficulty' %>
      <%= filter_difficulty.humanize %>
    <% end %>
<% end %>
	





<%= form_tag browse_series_index_path, remote: true, id: 'filter_module_form', class: 'filter_module'  do %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
<% [ 'Administration', 'Development', 'Intgeration'].each do |filter_module| %>
      <%= radio_button_tag 'filter_module', filter_module, @filter_module == filter_module %>
      <%= filter_module.humanize %>
    <% end %>
<% end %>





<%= form_tag browse_series_index_path, remote: true, id: 'filter_published_when_form', class: 'filter_published_when_form'  do %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
<% [ 'Last Week', 'Last Month','Last 6 Months', 'Last Year'].each do |filter_published_when_form| %>
      <%= radio_button_tag 'filter_published_when_form', filter_published_when_form, @filter_published_when_form == filter_published_when_form %>
      <%= filter_published_when_form.humanize %>
    <% end %>
<% end %>

app/views/series/_series_search.html.erb
<section class="search-inner">
        <div class="row">

<%= form_tag(search_series_index_path, method: :get) do %>
  <%= text_field_tag :search, params[:search], class: "search-box" %>
  <%= submit_tag 'Search', class: "btn btn-full" %>
<% end %>


<% if false %>
<%= render 'series_filter' %>
		<% end %>

         
        </div>

    </section>
        

app/views/series/browse.html.erb
<% if false %>
<%= render 'series_filter' %>


<% end %>



<%= render 'innerpages_header' %>

<%= render 'series_search' %>


<%= render 'series_list' %>


<%= render 'footer' %>

app/views/series/callback.html.erb
<%= render 'innerpages_header' %>


<section class="web-to-lead">
	<div class="row">
		<h2>Request Call Back</h2>
	</div>


<div class="row">
	
	<div class="col span-1-of-2">

		<div class="row" style="text-align: center;padding-bottom: 10px;">
			<h3>Most Popular Series</h3>
		</div>

		<div class="row">
            <% @series.each do |series| %>

			<div class="col span-1-of-3 box callback-box">
                <div class="recent-series">

                    <img src="<%= series.series_banner%>" class="callback-series-banner">
                    
                    <div class="recent-series-icard">
                        
                            <div class="series-title callback-box-title">
        
                            <%= link_to series.title,series_path(series) %>
                        </div>
                    </div>
                </div>
            </div>
            <%end -%>
		</div>
		 


		
	</div>
	
	<div class="col span-1-of-2">
		<form action="https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST">

		<input type=hidden name="oid" value="00D28000001NyDU">
		<input type=hidden name="retURL" value="http://salesforcecasts.com">
	
	<div class="row callback-fields">
		
			
			<input  id="last_name" maxlength="80" name="last_name" size="20" type="text" placeholder="Name" required/>
		
	<div class="row callback-fields">
		
			<input  id="mobile" maxlength="40" name="mobile" size="20" type="text" placeholder="Mobile" required/>
			
		
	</div>
	
	<div class="row callback-fields">
		
			<input  id="email" maxlength="80" name="email" size="20" type="email" placeholder="Email" required/>
	</div>
	
	<div class="row callback-fields">
		
			<select  id="00N2800000CIh1x" name="00N2800000CIh1x" title="Interested in?" required>
				<option value="">--None--</option>
				<option value="Complete Salesforce.com Training">Complete Salesforce.com Training</option>
				<option value="Salesforce.com Administration Training">Salesforce.com Administration Training</option>
				<option value="Salesforce.com Development Training">Salesforce.com Development Training</option>
				<option value="Salesforce.com 502/Integration Training">Salesforce.com Integration(501) Training</option>
			</select>
		
	</div>
	<div class="row callback-fields">
		
			<textarea name="description" placeholder="Question?"></textarea>

	</div>
	
	
	<div class="row callback-submit">
		<input type="submit" name="submit">
			
	
	</div>

</form>

	</div>
</div>
	



</section>



<%= render 'footer' %>

app/views/series/dashboard.html.erb
<%= render 'innerpages_header' %>


<h1>	Dashboard</h1>

<table border="1">
	


<% @series.each do |series| %>
<tr>
	
    <td><%= series.id %></td>  
	<td><%= link_to series.title, series_admin_view_path(series)%></td>	
	


	<% if user_signed_in? && current_user.admin? -%>
                <td><%= link_to 'edit', edit_series_path(series) %></td>
                <td><%= link_to 'delete', series,method: :delete, data: { confirm: 'Are you sure?' } %></td>
                
                <% if series.publish == true%>
                    <td><%= link_to 'un-publish', unpublish_series_path(series), method: :post %></td>
                <% else %>    
                    <td><%= link_to 'publish', publish_series_path(series), method: :post %></td>
                <% end %>
                <td><%= link_to 'add episode', new_series_episode_path(series) %></td>
            <% end %>

</tr>
	
<% end %>

</table>
<%= render 'footer' %>

app/views/series/delete.html.erb
<h1>Series#delete</h1>
<p>Find me in app/views/series/delete.html.erb</p>

app/views/series/edit.html.erb
<h1>Series#edit</h1>
<p>Find me in app/views/series/edit.html.erb</p>


<%= render 'form' %>

<%= render 'footer' %>

app/views/series/show_admin_view.html.erb
<table border="1">
  
  <tr>
    <td>Title</td>
    <td><%= @series.title %></td>
  </tr>
  <tr>
    <td>Description</td>
    <td><%= @series.description %></td>
  </tr>
  <tr>
    <td>No of Lessons</td>
    <td><%= @series.no_of_lessons %></td>
  </tr>
  <tr>
    <td>Difficulty</td>
    <td><%= @series.difficulty %></td>
  </tr>
  <tr>
    <td>Trailer</td>
    <td><%= @series.trailer %></td>
  </tr>
  <tr>
    <td>Rent Price</td>
    <td><%= @series.rent_price %></td>
  </tr>
  <tr>
    <td>Buyout Price</td>
    <td><%= @series.buyout_price %></td>
  </tr>
</table>

<table style="width: 1100px;">
<% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.id %></td> 
        <td><%= episode.episode_order %></td>
        <td><td><%= link_to episode.episode_title,series_episode_path(@series,episode) %></td>
        <td><%= episode.episode_description %></td>
        <td><%= episode.episode_video %></td>
        <td><%= episode.tags %></td>
        <td><%= episode.episode_type %></td>
        <td><%= episode.episode_duration %></td>

        <% if current_user.admin? -%>
          
          <td><%= link_to 'edit',edit_series_episode_path(@series,episode) %></td>
          <td><%= link_to 'delete',[@series,episode],method: :delete, data: { confirm: 'Are you sure?' } %></td>
        	
        
     	<% end -%>

      </tr>
    <% end %>
</table>

app/views/series/subscriptions.html.erb
<%= render 'innerpages_header' %>

<section class="section-subscriptions">
	
	<div class="row">
		<h2>Subscriptions</h2>

		<table class="subscription-table"> 

  <% if not @orders.empty? %> 
  <tr>
    <th>Title</th>
    <th>No of Lessons</th> 
    <th>Difficulty</th>
    <th>Purchased on</th>
  </tr>
  <% end -%>

 <% @orders.each do |order| %>
      <tr>
        <td>  <%= link_to order.series.title,order.series %></td>
        <td><%= order.series.no_of_lessons %></td>
        <td><%= order.series.difficulty %></td>
        <td><%= order.created_at.strftime("%m/%d/%y  %H:%M %p")    %></td>
        
     
        

      </tr>
    <% end %>


</table>
	</div>
</section>

<%= render 'footer' %>

app/views/series/users.html.erb
<%= render 'innerpages_header' %>


<h1>Users</h1>

<table border="1">
	<tr>
		<th>Email</th>
		<th>Admin?</th>
		<th>Current Sign In at</th>
		<th>Last Sign In at</th>
		<th>Sign In count</th>
	</tr>


<% @users.each do |user| %>
<tr>
	
    <td><%= user.email %></td>  
    <td><%= user.admin %></td>  
    <td><%= user.current_sign_in_at %></td>  
    <td><%= user.last_sign_in_at %></td>  

    <td><%= user.sign_in_count %></td>  
	

</tr>
	
<% end %>

</table>
<%= render 'footer' %>